name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  SECRET1:
    description: "test1"
    default: default_secret1
  SECRET2:
    description: "test2"
    default: default_secret2

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
